### ISSUE TITLE
Multiple croppers are not isolated

### ISSUE THREAD

**Issue by julianadormon** [CropperBlazor/Cropper.Blazor#168]
Hoping you can help. 

I have a problem when multiple croppers are present, events and data are not scoped to the component.
When a new cropper is created, it receives the events and data from another component.

I have made a video that shows the issue:

https://www.loom.com/share/5c86d0c9f1a04fa690d5a228d5bf15eb

The small cropper code:

```
<CropperComponent @key="id"
                                  InputAttributes="InputAttributes"
                                  Class="cropper-small"
                                  @ref="OdCropperComponent"
                                  Src="@OdmUrl"
                                  Options="@Options"
                                  OnReadyEvent="OnCropReadyEvent" />
```
                                  
                                  
 The large cropper code:
 
```
 <CropperComponent Class="cropper-large"
                                  @ref="CropperComponent"
                                  Src="@OdmUrl"
                                  Options="@Options"
                                  OnZoomEvent="(args) => OnZoomEvent(args)" />
```
                                  
   This the code that the buttons called within their own component.
   
   ```
public async Task ZoomIn()
    {
        OdCropperComponent.Zoom(2M);

        await InvokeAsync(() =>
        {
            StateHasChanged();
        });
    }

    public async Task Reset()
    {
        OdCropperComponent.Reset();

        await InvokeAsync(() =>
        {
            StateHasChanged();
        });
    }

```
As you can see the small cropper component, where these methods live, are targeting their proper ref, "OdCropperComponent", but after the larger cropper is created, when fired, the large cropper is receiving these events.

Similarly, once the large cropper is instantiated, when I try OdCropperComponent.GetData, I get the data from the large cropper.

Thanks!

**Comment by MaxymGorn** [comment]
Hi @julianadormon . I will look today that topic. I can only point out now that we use CorrelationId in Options and JSEventData<>, for distribution events for each type cropper
<img width="692" alt="image" src="https://github.com/CropperBlazor/Cropper.Blazor/assets/50423072/38623182-f475-4f11-895a-59940029ea78">

**Comment by julianadormon** [comment]
Thank you! I will try that and get back to you. I appreciate the help.

**Comment by julianadormon** [comment]
Unfortunately, that does not help. I have made another video:

https://www.loom.com/share/5e192a3b085e435488c27b8722d76ddc

**Comment by MaxymGorn** [comment]
Hi @julianadormon.
Can you provide any problem code for this one, can you create a github repository with this error, I will try to overcome this error. It looks very interesting. Thanks for the video!

**Comment by MaxymGorn** [comment]
After watching the latest video, it seems that it should work in your version without adding the CorrelationId.

**Comment by julianadormon** [comment]
Thanks. I will try, but it won't be for a few weeks. I decided to tackle the issue another way.

**Comment by MaxymGorn** [comment]
Okay @julianadormon, it seems that this cropper has not been tested and it is obvious that it is not designed for several active croppers at the same time, I would say that you need to think carefully about how to make all the components of the system connected correctly

**Comment by saadsaeed01** [comment]
Hello @MaxymGorn 
I hope you are doing well. I think I am facing the same problem with two cropper components. 
Case 1:
in this case, I have a single cropper component. I am setting SetData options whenever I am initializing the cropper. It works fine
![image](https://github.com/CropperBlazor/Cropper.Blazor/assets/33133831/2f134f1f-a4ff-46a1-8247-3d0688861935)
Data is persisted whenever I visit the **Theme** tab

Them tab before:
![image](https://github.com/CropperBlazor/Cropper.Blazor/assets/33133831/522398ad-0eba-4325-8ea0-87cc9e20d436)
Theme tab after visiting another tab and then going to this tab again:
![image](https://github.com/CropperBlazor/Cropper.Blazor/assets/33133831/118292d9-9034-4fd0-bf50-033f399daa5d)

Case 2:
In this case, I am using two croppers one for the logo and one for the strip image
Theme tab before:
![image](https://github.com/CropperBlazor/Cropper.Blazor/assets/33133831/345a67ec-7025-4ca0-8355-052aa58be14b)
Theme tab after:
![image](https://github.com/CropperBlazor/Cropper.Blazor/assets/33133831/effdf75e-e960-4827-8516-f05cec1cb4e4)

You can see that the strip image cropper is holding the position quite well but for the logo image cropper, the cropper position is getting disoriented

I hope I am clear about my problem.
Please confirm whether this issue is related to data isolation.

Waiting for your comments
Regards
S

**Comment by MaxymGorn** [comment]
@saadsaeed01 Yes, I confirm the problem of data isolation between two or more croppers! Unfortunately, the existing logic is designed for only one cropper in the [cropper component](https://github.com/CropperBlazor/Cropper.Blazor/blob/dev/src/Cropper.Blazor/Cropper.Blazor/Components/CropperComponent.razor) and [cropperJsInterop.js] (https://github.com/CropperBlazor/Cropper.Blazor/blob/dev/src/Cropper.Blazor/Cropper.Blazor/wwwroot/cropperJsInterop.js)

**Comment by MaxymGorn** [comment]
@saadsaeed01 Yes, I confirm the problem of data isolation between two or more croppers! Unfortunately, the existing logic is designed for only one cropper in the [cropper component](https://github.com/CropperBlazor/Cropper.Blazor/blob/dev/src/Cropper.Blazor/Cropper.Blazor/Components/CropperComponent.razor) and [cropperJsInterop.js] (https://github.com/CropperBlazor/Cropper.Blazor/blob/dev/src/Cropper.Blazor/Cropper.Blazor/wwwroot/cropperJsInterop.js). I will fix this issue in next version

**Comment by saadsaeed01** [comment]
@MaxymGorn 
Thank you very much!
Can you please confirm how much time you are expected to fix this issue?

**Comment by saadsaeed01** [comment]
@MaxymGorn 
I have checked it out
It creates more problems, especially with image previews, when I am changing from the theme tab to the fields tab. The strip image preview is disappearing
At themes tab
![image](https://github.com/CropperBlazor/Cropper.Blazor/assets/33133831/1d1b61ce-6521-4a25-843f-6cf3edbdc29b)
At fields tab
![image](https://github.com/CropperBlazor/Cropper.Blazor/assets/33133831/fdcaf11d-1a80-4ab2-8409-e78eadf9959b)
Strip image disappears

**Comment by MaxymGorn** [comment]
@saadsaeed01 Seems after destroy cropper component you need re-inti component:
`CropperComponent?.Destroy();           CropperComponent?.InitCropper();`

**Comment by saadsaeed01** [comment]
@MaxymGorn 
The problem still exists, Even if I am getting the wrong data
![image](https://github.com/CropperBlazor/Cropper.Blazor/assets/33133831/e5aebb36-cd6c-465c-9873-d3953e9c0a5b)

**Comment by MaxymGorn** [comment]
@saadsaeed01 Obviously, this is a specific work of the preview cropper.js library, so if you want to have a preview after you have left the Theme tab with the cropper.  You need to pre-save this image using the cropperComp.GetCroppedCanvasDataURL method and use the image result in the preview element. You don't need to use Destroy and re-init cropper in this case

**Comment by saadsaeed01** [comment]
@MaxymGorn 
Understood, but the cropperComp.GetCroppedCanvasDataURL is not giving the right information. On Click Me, I am using the same method but on both component's its giving me the same result which cropped image of the **Strip Image** component
![image](https://github.com/CropperBlazor/Cropper.Blazor/assets/33133831/6d8d4ad0-24c4-4c0f-8a5c-64dc541946ef)

**Comment by saadsaeed01** [comment]
@MaxymGorn Ok thanks a lot, waiting for your fix

**Comment by MaxymGorn** [comment]
PR: https://github.com/CropperBlazor/Cropper.Blazor/pull/178

**Comment by MaxymGorn** [comment]
Hi @saadsaeed01 , @julianadormon could you provide information about working isolation multiple active croppers from this branch [fix/isolation_multiple_active_croppers](https://github.com/CropperBlazor/Cropper.Blazor/tree/fix/isolation_multiple_active_croppers) (PR: https://github.com/CropperBlazor/Cropper.Blazor/pull/178)

**Comment by saadsaeed01** [comment]
Hi @MaxymGorn 
Thank you for the effort!
The problem is still there
![image](https://github.com/CropperBlazor/Cropper.Blazor/assets/33133831/800aa5dc-df0f-4082-9ff3-717ebbe21051)
 
I clone the repository and switched to `fix/isolation_multiple_active_croppers` branch
![image](https://github.com/CropperBlazor/Cropper.Blazor/assets/33133831/2545e634-de24-49c0-8d9c-53acf7d82045)

Remove the NuGet from my application and attached the Cropper.Blazor library like this
![image](https://github.com/CropperBlazor/Cropper.Blazor/assets/33133831/10114c4e-7c34-4e7a-adec-84daa59d8fbf)

The cache is disabled to load the latest content
![image](https://github.com/CropperBlazor/Cropper.Blazor/assets/33133831/986b9d47-0788-466c-8798-0fa35c16ff69)

**NOTE**
The version of visual studio that I am using doesn't support .NET 7 so I have to remove .NET 7 as the target framework
![image](https://github.com/CropperBlazor/Cropper.Blazor/assets/33133831/e656d89e-70cf-468c-b704-2710865313f4)

**Comment by MaxymGorn** [comment]
@saadsaeed01 Ok, can you provide the code data how you use these croppers, I have a sample where my croppers are compatible with each other, I can provide them in about 4 hours

**Comment by saadsaeed01** [comment]
Ok Sure here you go:

ImageUploaderComponent.razor and ImageUploaderComponent.razor.cs(Child components)
`@using Cropper.Blazor.Components
<style>
    .mud-icon-button {
        padding: 0px !important;
    }
</style>

<div class="imageuploadcontainer mb-2">
    @if (_processing == false)
    {
        @if (string.IsNullOrEmpty(ImageDetails.ActualImage))
        {
            <MudFileUpload T="IBrowserFile" FilesChanged="UploadFilesAsync" Accept="image/*">
                <ButtonTemplate>
                    <MudIconButton Style=" padding-right: 6px !important;padding-bottom: 3px !important;"
                           HtmlTag="label"
                           Color="Color.Info"
                           Icon="@Icons.Material.Filled.Upload"
                           for="@context">
                    </MudIconButton>
                </ButtonTemplate>
            </MudFileUpload>

        }
        else
        {
            <MudIconButton Style=" padding-right: 6px !important;padding-bottom: 3px !important;"
                   HtmlTag="label"
                   Color="Color.Info"
                   OnClick="RemoveImage"
                   Icon="@Icons.Material.Filled.Close">
            </MudIconButton>
        }
    }
    else
    {
        <MudProgressCircular Class="ms-n1" Size="Size.Small" Indeterminate="true" />
    }
</div>
@if (!string.IsNullOrEmpty(ImageDetails.ActualImage))
{
    <div class="@GetClassNameCropper() ml-1">
        <CropperComponent 
            Class="cropper-container"
            ErrorLoadImageClass="cropper-error-load"
            @ref="CropperComponent"
            OnCropEndEvent="OnCropEndEventAsync"
            Src="@ImageDetails.ActualImage"
            Options="Options"
            IsAvaibleInitCropper="true" />
    </div>
}

<MudButton OnClick="CroppedImage" >Crop Image</MudButton>
@if(!string.IsNullOrEmpty(_croppedImage))
{
    <MudImage Src="@_croppedImage" />

}`

`
using Common.Enums;
using Cropper.Blazor.Components;
using Cropper.Blazor.Events.CropEvent;
using Cropper.Blazor.Events;
using Cropper.Blazor.Models;
using DigitalBusinessCardContext.Models.NotMapped;
using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Components.Forms;
using Microsoft.Graph;
using Microsoft.JSInterop;
using MudBlazor;
using Cropper.Blazor.Events.CropEndEvent;
using Cropper.Blazor.Extensions;

namespace ManagementPortal.Components.Controls
{
    public partial class ImageUploaderComponent
    {
        #region Parameters
        [Parameter] public CropperFaceEnum CropperFace { get; set; } = CropperFaceEnum.Default;
        [Parameter] public string? DefaultImage { get; set; }
        [Parameter] public decimal Width { get; set; }
        [Parameter] public decimal Height { get; set; }
        [Parameter] public ElementReference ImagePreviewReference { get; set; }

        [Parameter, EditorRequired] public ImageDetails ImageDetails { get; set; }
        #endregion

        #region Dependencies
        [Inject] private ISnackbar _snackbar { get; set; }
        [Inject] private ILogger<ImageUploaderComponent> _logger { get; set; }
        [Inject] private IJSRuntime _jSRuntime { get; set; }
        #endregion

        #region Helper variables
        private CropperComponent? CropperComponent = null!;
        const int MAX_IMAGE_UPLOADSIZE = 20480000;
        private Options Options = null!;
        bool _processing = false;
        private string _croppedImage;
        public ElementReference imagePreviewReference { get; set; }
        #endregion




        public void ResetCropper()
        {
            CropperComponent?.Destroy();
            CropperComponent?.RevokeObjectUrlAsync(ImageDetails.ActualImage);
            CropperComponent?.InitCropper();
        }

        protected override void OnInitialized()
        {
            Options = new Options()
            {
                AspectRatio = Width / Height,
                ViewMode = ViewMode.Vm0,
                CorrelationId = Guid.NewGuid().ToString(),
                SetDataOptions = new SetDataOptions
                {
                    Height = ImageDetails?.MetaData?.Height,
                    Width = ImageDetails?.MetaData?.Width,
                    ScaleX = ImageDetails?.MetaData?.ScaleX,
                    ScaleY = ImageDetails?.MetaData?.ScaleY,
                    X = ImageDetails?.MetaData?.X,
                    Y = ImageDetails?.MetaData?.Y,
                    Rotate = ImageDetails?.MetaData?.Rotate,

                }
            };
            if (ImageDetails != null && ImageDetails.ActualImage == null && DefaultImage != null)
            {
                ImageDetails.ActualImage = DefaultImage;
            }
        }

        protected override void OnAfterRender(bool firstRender)
        {
            if (firstRender && ImagePreviewReference.Context is not null)
            {
                Options.Preview = new ElementReference[]
                {
                   ImagePreviewReference
                };
            }
        }



        private string GetClassNameCropper() =>
            "img-container" + CropperFace switch
            {
                CropperFaceEnum.Default => string.Empty,
                CropperFaceEnum.Close => " cropper-face-close",
                CropperFaceEnum.Pentagon => " cropper-face-pentagon",
                CropperFaceEnum.Circle => " cropper-face-circle",
                CropperFaceEnum.Arrow => " cropper-face-arrow",
                _ => string.Empty,
            };



        private async Task UploadFilesAsync(IBrowserFile e)
        {
            try
            {
                _processing = true;
                ValidateImage(e);
                var dotnetImageStream = new DotNetStreamReference(e.OpenReadStream(MAX_IMAGE_UPLOADSIZE));
                var result = await _jSRuntime.InvokeAsync<string>("setImageInABlob", dotnetImageStream);
                ImageDetails.ActualImage = result;
                StateHasChanged();
            }
            catch (Exception ex)
            {

                _logger.LogError(ex, "Theme component");
                _snackbar.Add(ex.Message, Severity.Error);
            }
            finally
            {
                _processing = false;
            }
        }

        private async Task CroppedImage()

        {
            _croppedImage = await GetCroppedCanvasDataURL();
            StateHasChanged();
        }

        public async void OnCropEndEventAsync(JSEventData<CropEndEvent> cropEndJSEvent)
        {

            var result = await CropperComponent!.GetDataAsync(false);
            if (result is not null)
            {
                ImageDetails.MetaData.ScaleX = result.ScaleX;
                ImageDetails.MetaData.ScaleY = result.ScaleY;
                ImageDetails.MetaData.Height = result.Height;
                ImageDetails.MetaData.Width = result.Width;
                ImageDetails.MetaData.X = result.X;
                ImageDetails.MetaData.Y = result.Y;
                ImageDetails.MetaData.Rotate = result.Rotate;
            }
        }

        private async void OnCropEventAsync(JSEventData<CropEvent> cropJSEvent)
        {
            if (cropJSEvent?.Detail is not null)
            {

            }
        }

        public async Task<CropperData> GetMetaDataAsync(bool rounded = false)
        {
            var result = await CropperComponent!.GetDataAsync(rounded);
            return result;
        }

        public async Task<string> GetCroppedCanvasDataURL()
        {
            var settings = new GetCroppedCanvasOptions() { MaxHeight = Height, MaxWidth = Width, ImageSmoothingQuality = ImageSmoothingQuality.High.ToEnumString() };
            string croppedCanvasDataURL = await CropperComponent!.GetCroppedCanvasDataURLAsync(settings);
            return croppedCanvasDataURL;
        }

        private void RemoveImage()
        {
            CropperComponent?.RevokeObjectUrlAsync(ImageDetails.ActualImage);
            ImageDetails.ActualImage = string.Empty;
            ImageDetails.CroppedImage = string.Empty;
            StateHasChanged();
        }

        private static void ValidateImage(IBrowserFile e)
        {
            var imageExtension = GetFileExtension(e);
            if (imageExtension != "png" && imageExtension != "jpeg" && imageExtension != "jpg")
            {
                throw new Exception("The given format is not supported");
            }
            if (e.Size > MAX_IMAGE_UPLOADSIZE)
            {
                throw new Exception("Image size too large. Please upload an image of size less than 20MB.");

            }
        }
        private static string GetFileExtension(IBrowserFile e)
        {
            string[] fileNameParts = e.Name.Split('.');
            string extensionPart = fileNameParts[fileNameParts.Count() - 1].Trim().ToLower();
            return extensionPart;
        }
    }
}
`
Theme. razor and Theme.razor.cs (Parent component)
`
@*Image croppers *@

<div class="d-flex flex-column gap-2 ">
    <div class="d-flex flex-column" style="max-width: 31%;">
        <MudText Typo="Typo.body2" Class="mt-5 ml-2 mb-2">Logo Image</MudText>
        <ImageUploaderComponent @ref=_logoImagePreviewComponentReference ImageDetails="CardGroup.LogoImageDetails" DefaultImage="@(ImageConstants.LogoImage)" ImagePreviewReference="LogoImagePreviewReference" Width="160" Height="50" />
    </div>
    <div class="d-flex flex-column" style="max-width: 31%;">
        <MudText Typo="Typo.body2" Class="mt-5 ml-2 mb-2">Strip Image</MudText>
        <ImageUploaderComponent @ref=_stripImagePreviewComponentReference ImageDetails="CardGroup.StripImageDetails" DefaultImage="@(ImageConstants.StripImage)" ImagePreviewReference="StripImagePreviewReference" Width="375" Height="123" />
    </div>
</div>
`
`
using Cropper.Blazor.Models;
using DigitalBusinessCardContext.Models;
using ManagementPortal.Components.Controls;
using ManagementPortal.Components.Dialogs;
using ManagementPortal.Models.BusinessCards;
using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Components.Forms;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using Microsoft.Graph;
using Microsoft.JSInterop;
using MudBlazor;
using Stripe;
using static MudBlazor.CategoryTypes;
using static MudBlazor.Colors;

namespace ManagementPortal.Components.CardDesignerTabs
{
    public partial class Theme 
    {
        #region Dependencies
        [Inject] private IDialogService _dialogService { get; set; }

        [Inject] private ISnackbar _snackbar { get; set; }
        [Inject] private ILogger<Theme> _logger { get; set; }
        #endregion

        #region Parameters
        [Parameter] public BusinessCard CardGroup { get; set; }
        [Parameter] public EventCallback NotifyChange { get; set; }
        [Parameter] public ElementReference LogoImagePreviewReference { get; set; }
        [Parameter] public ElementReference StripImagePreviewReference { get; set; }



        #endregion

        #region Helper variables
        ImageUploaderComponent _logoImagePreviewComponentReference { get; set; }
        ImageUploaderComponent _stripImagePreviewComponentReference { get; set; }

        #endregion

        #region Helping Methods 

        public async Task<string> GetCroppedImageForLogoAsync()
        {
            return await _logoImagePreviewComponentReference.GetCroppedCanvasDataURL();
        }

        public async Task<CropperData> GetMetaDataForLogoAsync()
        {
            return await _logoImagePreviewComponentReference.GetMetaDataAsync(false);
        }

        public async Task<string> GetCroppedImageForStripAsync()
        {
            return await _stripImagePreviewComponentReference.GetCroppedCanvasDataURL();
        }

        public async Task<CropperData> GetMetaDataForStripAsync()
        {
            return await _stripImagePreviewComponentReference.GetMetaDataAsync(false);
        }

        public void ResetImageCroppers()
        {
            _logoImagePreviewComponentReference.ResetCropper();
            _stripImagePreviewComponentReference.ResetCropper();
        }

        private async Task NotifyBackgroundColorChangedAsync()
        {
            await NotifyChange.InvokeAsync();
        }

        private async Task NotifyLabelColorChangedAsync()
        {
            await NotifyChange.InvokeAsync();
        }
        #endregion
    }
}
`

**Comment by saadsaeed01** [comment]
@MaxymGorn  Does this work?

**Comment by MaxymGorn** [comment]
@saadsaeed01 I pushed code with example using 2 active croppers
<img width="889" alt="image" src="https://github.com/CropperBlazor/Cropper.Blazor/assets/50423072/0196b5f2-0126-415e-b19e-51529c75c646">
Just pull "https://github.com/CropperBlazor/Cropper.Blazor/tree/example_multiple_active_croppers" branch and go to this URL: https://localhost:7025/api

**Comment by MaxymGorn** [comment]
It looks like when you used your cropper you used the same link for 2 croppers:
<img width="443" alt="image" src="https://github.com/CropperBlazor/Cropper.Blazor/assets/50423072/1cabc7ca-d989-410e-943b-562b05727258">

**Comment by saadsaeed01** [comment]
Hi @MaxymGorn 
Thanks for the effort
Referring to 
_It looks like when you used your cropper you used the same link for 2 croppers:_

It's not correct, the reason is that this is just a component, It has a single reference because an element has a single cropper. I am calling my component twice as given below:

`@*Image croppers *@

<div class="d-flex flex-column gap-2 ">
    <div class="d-flex flex-column" style="max-width: 31%;">
        <MudText Typo="Typo.body2" Class="mt-5 ml-2 mb-2">Logo Image</MudText>
        <ImageUploaderComponent @ref=_logoImagePreviewComponentReference ImageDetails="CardGroup.LogoImageDetails"  ImagePreviewReference="LogoImagePreviewReference" Width="160" Height="50" />
    </div>
    <div class="d-flex flex-column" style="max-width: 31%;">
        <MudText Typo="Typo.body2" Class="mt-5 ml-2 mb-2">Strip Image</MudText>
        <ImageUploaderComponent @ref=_stripImagePreviewComponentReference ImageDetails="CardGroup.StripImageDetails"  ImagePreviewReference="StripImagePreviewReference" Width="375" Height="123" />
    </div>
    <div class="d-flex flex-column" style="max-width: 31%;">
        <MudText Typo="Typo.body2" Class="mt-5 ml-2 mb-2">Background color</MudText>
        <MudColorPicker Class="pl-2" @bind-Text="CardGroup.BackgroundColor" Placeholder="Select Color" ValueChanged="@NotifyBackgroundColorChangedAsync" />
    </div>
    <div class="d-flex flex-column" style="max-width: 31%;">
        <MudText Typo="Typo.body2" Class="mt-5 ml-2 mb-2">Font color</MudText>
        <MudColorPicker  @bind-Text="CardGroup.LabelColor" Class="pb-4 pl-2" Placeholder="Select Color" ValueChanged="@NotifyLabelColorChangedAsync" />
    </div>
</div>

`

**Comment by saadsaeed01** [comment]
Hi @MaxymGorn 
I do think there is some issue with porting on my side. I used the same code that you provided in your example and used it in my application and not working correctly
For big image, it's giving me the data related to the small images
![image](https://github.com/CropperBlazor/Cropper.Blazor/assets/33133831/8fad16e9-ba3e-4854-8154-01388ae82b62)
Can you please confirm when will you merge this update?

**Comment by saadsaeed01** [comment]
@MaxymGorn 
I am still getting the old cropperJsInterop.min.js, I have cleared the browser cache, but I do think there is some issue with how I have linked the project. Waiting for your merge so I can check it using the Nuget package
![image](https://github.com/CropperBlazor/Cropper.Blazor/assets/33133831/5208de75-723b-4aa9-8cd1-fa83512cd0a9)

**Comment by saadsaeed01** [comment]
Hi @MaxymGorn 
The issue was that NuGet was still being used in the project. I have removed it and linked the project Cropper.Blazor, it now gives this error:
`Cannot consume scoped service 'Microsoft.JSInterop.IJSRuntime' from singleton 'Cropper.Blazor.Services.ICropperJsInterop'.`
Can you please check out this issue?
I am using Blazor Server and my NET version is 6

**Comment by saadsaeed01** [comment]
Hi @MaxymGorn 
The problem is solved the data isolation issue is solved
![image](https://github.com/CropperBlazor/Cropper.Blazor/assets/33133831/0c25c2e8-abcf-4ebb-93a2-391883bfeed5)
I had to change the service lifetime from singleton to scoped
![image](https://github.com/CropperBlazor/Cropper.Blazor/assets/33133831/b3ffe37a-a3e6-4cde-a05f-821037372d54)
I don get it, you have changed it in your PR too. What is the reason?

**Comment by MaxymGorn** [comment]
> Hi @MaxymGorn 
> The problem is solved the data isolation issue is resolved
> ![image](https://github.com/CropperBlazor/Cropper.Blazor/assets/33133831/0c25c2e8-abcf-4ebb-93a2-391883bfeed5)
> I had to change the service lifetime from singleton to scoped
> ![image](https://github.com/CropperBlazor/Cropper.Blazor/assets/33133831/b3ffe37a-a3e6-4cde-a05f-821037372d54)
> I don't get it, you have changed it in your PR too. What is the reason?

Hi @saadsaeed01, thanks for your contribution, I'll fix it!

**Comment by saadsaeed01** [comment]
Hi @MaxymGorn 
Can you please confirm that in how much time the changes will be merged

**Comment by MaxymGorn** [comment]
> Hi @MaxymGorn 
> Can you please confirm that in how much time the changes will be merged

I push this fix this PR: https://github.com/CropperBlazor/Cropper.Blazor/pull/178, after merging with dev I'll push publishing nuget in master branch

**Comment by saadsaeed01** [comment]
@MaxymGorn  
So in approx how much time the NuGet will be available?

**Comment by MaxymGorn** [comment]
> @MaxymGorn  
> So in approx how much time the NuGet will be available? 

I think in the next hour or an hour and a half the package will be available

**Comment by saadsaeed01** [comment]
@MaxymGorn Sound's great. Kindly mention to me when it's available. :)

**Comment by MaxymGorn** [comment]
@saadsaeed01 You can try to install 1.2.4 package using cli or another way:
<img width="727" alt="image" src="https://github.com/CropperBlazor/Cropper.Blazor/assets/50423072/dfe4d200-45be-4872-81db-7047bd96345b">

**Comment by MaxymGorn** [comment]
Package was indexed yet 
<img width="566" alt="image" src="https://github.com/CropperBlazor/Cropper.Blazor/assets/50423072/6eb6c14a-f04f-42d8-b782-55525ba3b8ec">

**Comment by MaxymGorn** [comment]
@saadsaeed01 could you provide me feedback on the correctness of this package?

**Comment by saadsaeed01** [comment]
@MaxymGorn It looks fine to me, I don't see any issues yet
![image](https://github.com/CropperBlazor/Cropper.Blazor/assets/33133831/ba0a3af9-95ac-4b6d-af96-1e19f1dc76db)

**Comment by MaxymGorn** [comment]
Hi @saadsaeed01 Is this error still relevant after the deployment of the new version of the package 1.2.4 in this issue: https://github.com/CropperBlazor/Cropper.Blazor/issues/177?

**Comment by saadsaeed01** [comment]
hi @MaxymGorn 
We have changed our approach and we are not using this approach now
